wikidata:
  output_dir_collect_instance_subclass: /dlabdata1/braemy/wikidata-b_classification
  #output_dir: /dlabdata1/braemy/wikidata-b_classification/data2017-05-10_13-07-33-716641
  output_dir: /dlabdata1/braemy/wikidata-b_classification/data2017-06-22_17-06-42-74450/
  id_to_subclass: id_subclass_of_dict
  id_to_instance: id_instance_of_dict
  id_to_title: id_title_dict
  title_to_id: title_id_dict
  wd_to_NER: /dlabdata1/braemy/wikidata-b_classification/mapping_wikidata_to_NER.p

graph_id_to_vertex: /dlabdata1/braemy/wikidata-b_classification/graph_id_to_vertex.p
graph: /dlabdata1/braemy/wikidata-b_classification/graph.xml.gz


output_folder: /dlabdata1/braemy/wikidataNER


#Build Dataset#
dataset_builder:
  wikidataNER_folder: /dlabdata1/braemy/wikidataNER
  input_folder: /dlabdata1/braemy/data
  wd_to_NER: /dlabdata1/braemy/wikidataNER/mapping_wikidata_to_NER.p
  hadoop_folder: hdfs://iccluster050/user/braemy
  wikidata_dump: 20170622
  conll_folder: /dlabdata1/braemy/nerc-conll2003
  de:
    language: de
    personal_title_threshold: 3
    wiki_dump: 20170620
    filter: 0.001
    method: wp3
    num_executors: 50
    list_of:
      - Liste
    section_to_remove:
      - Siehe auch
      - Literatur
      - Weblinks
      - Anmerkungen
    keep_table: True
  en:
    language: en
    list_of:
      - "List of"
      - "Lists of"
    section_to_remove:
      - External links
      - Further reading
      - References
      - See also
    personal_title_threshold: 2
    wiki_dump: 20170620 #20170301
    filter: 0.05
    method: wp3
    num_executors: 50
    keep_table: True
    #subpart: team



  als:
    language: als
    personal_title_threshold: 3
    wiki_dump: 20170620
    filter: 1
    method: wp2
    num_executors: 20
    list_of:
      - Liste
    section_to_remove:
      - Lueg au
      - Weblink
      - Literatur
      - Referänze
      - Fuessnoote
    keep_table: True

